//
// Created by Karol Nalepa on 19/05/2026.
//

#ifndef PROJEKT2_NALEPA_PETELICKI_PIECES_H
#define PROJEKT2_NALEPA_PETELICKI_PIECES_H

enum Piece {
    NONE,

    WHITE_PAWN,
    WHITE_KNIGHT,
    WHITE_BISHOP,
    WHITE_ROOK,
    WHITE_QUEEN,
    WHITE_KING,

    BLACK_PAWN,
    BLACK_KNIGHT,
    BLACK_BISHOP,
    BLACK_ROOK,
    BLACK_QUEEN,
    BLACK_KING
};

#endif //PROJEKT2_NALEPA_PETELICKI_PIECES_H
